# Generated by Django 2.2.2 on 2019-06-15 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetails',
            name='user_code',
            field=models.IntegerField(null=True),
        ),
    ]
