# Generated by Django 2.2.2 on 2019-06-15 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_bankdetails_user_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankdetails',
            name='user_code',
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
