# Generated by Django 2.2.2 on 2019-06-29 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20190615_1023'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='employee_id',
        ),
    ]
